services:
  - postgresql
language: node_js
node_js:
  - 10.14.1
branches:
  only:
    - develop
    - /^greenkeeper/.*$/
install:
  - npm install
cache:
  directories:
    - node_modules
after_success: npm run coverage
