# services:
#   - postgresql
# language: node_js
# node_js:
#   - 10.14.1
# branches:
#   only:
#     - develop
# install:
#   - npm install
# cache:
#   directories:
#     - node_modules
# after_success: npm run coverage

language: node_js
node_js:
  - 'node'
branches:
  only:
    - develop
    - /^greenkeeper.*$/
services:
  - postgresql
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
env:
  global:
    - PGPORT=5433
    - DB_NAME=teamworktest
    - DB_USER=teamwork
before_script:
  - psql --command="CREATE USER ${DB_USER};"
  - psql --command="CREATE DATABASE ${DB_NAME} WITH OWNER = ${DB_USER};"
  - psql --dbname=$DB_NAME --file=sql/create-tables.sql
install:
  - npm install
cache:
  directories:
    - 'node_modules'
after_success: npm run coverage
